openapi: 3.0.3
info:
  title: NVA Courses API
  version: 1.0.0
paths:
  /:
    get:
      summary: Get currently taught courses
      security:
        - CognitoUserPool: ['https://api.nva.unit.no/scopes/backend', 'https://api.nva.unit.no/scopes/frontend', 'aws.cognito.signin.user.admin']
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CurrentlyTaughtCoursesFunction.Arn}/invocations
        responses: { }
        httpMethod: POST
        type: AWS_PROXY
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  courses:
                    required: true
                    type: array
                    items:
                      $ref: '#/components/schemas/Course'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  schemas:
    Course:
      type: object
      properties:
        code:
          required: true
          type: string
        year:
          required: true
          type: integer
        term:
          required: true
          type: string
    Problem:
      type: object
      properties:
        title:
          type: string
        status:
          type: integer
        detail:
          type: string

  securitySchemes:
    CognitoUserPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - Ref:
              CognitoAuthorizerArn