openapi: 3.0.3
info:
  title: NVA Video Management System API
  version: 1.0.0
paths:
  /:
    get:
      summary: Get video presentations for the current user from the integrated VMS
      security:
        - CognitoUserPool: [ 'https://api.nva.unit.no/scopes/backend', 'https://api.nva.unit.no/scopes/frontend', 'aws.cognito.signin.user.admin' ]
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${NvaVideoPresentationsFunction.Arn}/invocations
        responses: { }
        httpMethod: GET
        type: AWS_PROXY
      parameters:
        - in: query
          name: size
          description: The numbers of results requested. Defaults to 10.
        - in: query
          name: offset
          description: The offset to get results from. Defaults to 0.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PagedResult'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  schemas:
    PagedResult:
      type: object
      properties:
        type:
          type: string
        @context:
          type: string
        id:
          type: string
        results:
          type: array
          items:
            $ref: '#/components/schemas/VideoPresentation'
        totalSize:
          type: integer
        nextResults:
          type: string
        previousResults:
          type: string

    VideoPresentation:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        timeRecorded:
          type: string
        presenter:
          type: string
        downloadUrl:
          type: string
        streamingUrl:
          type: string
        thumbnailUrl:
          type: string
        contentIdentifier:
          type: string

    Problem:
      type: object
      properties:
        title:
          type: string
        status:
          type: integer
        detail:
          type: string

  securitySchemes:
    CognitoUserPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - Ref:
              CognitoAuthorizerArn