openapi: 3.0.0
info:
  version: '1.0'
  title: DLR VMS Service API
  license:
    name: MIT
paths:
  /presentations/{offset}{pageSize}:
    get:
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: pageSize
          schema:
            type: integer
          description: The numbers of items to return
      summary: Fetch VMS resources in DLR
      operationId: vms
      tags:
        - panopto
        - kaltura
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${VMSIntegrationServiceFunction.Arn}/invocations
        httpMethod: POST
        type: AWS_PROXY
      responses:
        '200':
          description: Request has succeeded

        '500':
          description: Unexpected error







